In [1]:
!uv pip install --no-progress pandas

Resolved 6 packages in 339ms
Downloading pandas (11.8MiB)
Downloading numpy (16.0MiB)
 Downloading pandas
 Downloading numpy
Prepared 2 packages in 1.01s
Installed 4 packages in 53ms
 + numpy==2.2.6
 + pandas==2.3.2
 + pytz==2025.2
 + tzdata==2025.2

In [2]:
import  pandas as pd

In [7]:
contributors = pd.read_csv("https://raw.githubusercontent.com/NixOS/SC-election-2025/refs/heads/main/contributors.csv", skiprows=1)
contributors

                  githubId         githubUsername  commits  merges
0                100007968           VulpesDaemon        1       0
1                100240294     florian-sanders-cc       10       0
2                100245234  joshheinrichs-shopify       12       0
3                100319043                  H3rmt        1       0
4                 10039785                  jsoo1       50       0
...                    ...                    ...      ...     ...
7390  MDM6Qm90MjY2MzQyOTI=                   bors        0     137
7391  MDM6Qm90MjkxMzk2MTQ=               renovate      118      13
7392  MDM6Qm90Mzc5MjkxNjI=                mergify      781     805
7393  MDM6Qm90NDE4OTgyODI=         github-actions    19464      29
7394  MDM6Qm90NDk2OTkzMzM=             dependabot      684       1

[7395 rows x 4 columns]

In [ ]:
contributors.sort_values('commits', ascending=False).reset_index().query('githubUsername == "lucasew"')

     index  githubId githubUsername  commits  merges
174   1489  15693688        lucasew      262       0

In [ ]:
contributors.sort_values('commits', ascending=False).reset_index().head(10)

   index              githubId   githubUsername  commits  merges
0   1909               1785925           vcunat    50347    2641
1    525                116184           fabaff    25031   17005
2    942                131599         mweinelt    21926    7602
3   7393  MDM6Qm90NDE4OTgyODI=   github-actions    19464      29
4   7385        BOT_kgDOC1l7FQ       nixpkgs-ci     6727       0
5   6001               6806011        dotlambda     4572    2673
6   3375               3154475   sternenseemann     4550     829
7   6256               7258858  SuperSandro2000     4238   14740
8   3498              33058747     GaetanLepage     3752    2835
9   7089               9132420  wolfgangwalther     3324    3681

In [16]:
contributors.sort_values('merges', ascending=False).reset_index().head(10)

   index        githubId     githubUsername  commits  merges
0   1411        15247171            NickCao     2189   26281
1   7274         9713184             wegank     2787   18332
2    525          116184             fabaff    25031   17005
3   6256         7258858    SuperSandro2000     4238   14740
4   5851           65531             marsam     2382    8815
5    942          131599           mweinelt    21926    7602
6   2805          252042             drupol     1486    6109
7   4202        42209822          Aleksanaa      600    4825
8   2195        20080233        bobby285271     3029    4805
9   7387  BOT_kgDOCNWgFA  nixpkgs-merge-bot        0    4725